API_CREDS:
  USER: test_user
  PASS: test_pass
DB_CREDS:
  HOST: localhost
  DB: postgres
  PORT: 5432
  USER: postgres
  PASS: mysecretpassword
  DRIVER: postgres
ABC:
  URL:  https://api.github.com/users/mralexgray/repos           # dummy url
  USER: some_user
  PASS: some_pass
DEF:
  URL: https://api.chucknorris.io/jokes/random # dummy url
PROXY:
  Address: ""
LOG_LEVEL: -1 #debug