GET http://localhost:1111/health

###

POST http://localhost:1111/api/register
Authorization: Basic test_user test_pass
Content-Type: application/json

{
    "id": "111",
	"returnUrl": "google.com/proceed",
	"failUrl": "gogle.com/fail",
	"billNumber": "111",
	"expirationDate": "2022-01-01"
}